### ISSUE TITLE
[BUG] Deleting a task will not refresh predecessors.

### ISSUE THREAD

**Issue by engrleir** [alexiusacademia/easyplan#2]
Example, I have task a->b->c->d, -> means a is a predecessor of b etc.

when I delete b, task 'd' predecessor (which is set as task 'c' or task number 3) does not update correctly... Please check

**Comment by alexiusacademia** [comment]
yes it will be updated/fixed in the core package.

**Comment by alexiusacademia** [comment]
Predecessor of a task is now refreshed by listening to an event and updating the ```Project``` class. This is now fixed.
